### ISSUE TITLE
failed to build rild

### ISSUE THREAD

**Issue by YumeMichi** [ashwinr64/android_device_oneplus_onyx#15]
```
/root/cm/out/target/product/onyx/obj/EXECUTABLES/rild_intermediates/rild.o:hardware/ril-caf/rild/rild.c:s_rilEnv: error: undefined reference to 'RIL_onRequestAck'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by YumeMichi** [comment]
Releated to https://github.com/ashwinr64/android_device_oneplus_onyx/commit/ce392434825a5bbf614a1a44d3ed960be3f94721

**Comment by YumeMichi** [comment]
OK! I got prebuilt rild, librilutils.so and libreference-ril.so from OOS 3.1.3

**Comment by jkimpel** [comment]
Hey, I'm having this exact issue. How did you get the rest of the build to complete without this stopping everything?

**Comment by YumeMichi** [comment]
@jkimpel I just pulled some libs from OOS, but It seems not work well. Hope to receive ashwinr64's reply.

**Comment by ashwinr64** [comment]
Try using cm-13.0-caf branch of hardware_ril.

**Comment by YumeMichi** [comment]
Now I am using cm-13.0-caf branch and build passed.
But there is a problem. If I connect to wifi and then disconnect it, mobile data won't work until next reboot. Turn on/off airplane mode also have the same problem.

**Comment by YumeMichi** [comment]
Does someone has any idea?

**Comment by YumeMichi** [comment]
Fixed:lol https://github.com/ashwinr64/android_device_oneplus_onyx/commit/07d11af40c5530a00e047374edc53749f1b3187f
